package com.example.code

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.material3.Button
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.code.ui.theme.CodeTheme
import kotlinx.coroutines.delay
import kotlin.math.pow
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

// Class MainActivity is used to display the game, and incorporates
// the game logic. Due to the simplicity of the game, the majority
// of the code is in the MainScreen() function. However, if the game
// were to be more complex, functionalities such as the different game
// menus could be separated into their own functions.

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        val game = Game()
        setContent {
            CodeTheme {
                MainScreen(
                    modifier = Modifier,
                    game = game
                )
            }
        }
    }
}

@OptIn(ExperimentalTime::class)
@Composable
fun MainScreen(modifier: Modifier = Modifier, game: Game) {

    var showMain by remember { mutableStateOf(true) }
    var showGame by remember { mutableStateOf(false) }
    var showLog by remember { mutableStateOf(false) }
    var showSummary by remember { mutableStateOf(false) }

    var sequenceLen by remember { mutableIntStateOf(-1) }
    var sequence by remember { mutableIntStateOf(-1) }
    var userGuess by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf(false) }
    var seqDisplayed by remember { mutableStateOf(false) }
    var guessed by remember { mutableStateOf(false) }
    var outcome by remember { mutableIntStateOf(-1) }
    var currentDigit by remember {mutableStateOf("")}
    var attemptCount by remember { mutableIntStateOf(0)}
    var correctCount by remember { mutableIntStateOf(0)}

    if (showMain) {
        Column(modifier.fillMaxSize()) {
            Row(modifier.fillMaxWidth().padding(30.dp), horizontalArrangement = Arrangement.Center) {
                Text("Welcome to Rapid Recall!")
            }
            Row(modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
                Button(onClick = {
                    showMain = false
                    showGame = true
                })
                { Text("Start") }
                Button(onClick = {
                    showMain = false
                    showLog = true

                })
                { Text("Log") }
                Button(onClick = {
                    showMain = false
                    showSummary = true
                })
                { Text("Attempt Summary") }
            }
        }
    }

    if (showGame) {
        Column(modifier.fillMaxSize()) {
            Row(modifier.fillMaxWidth().padding(30.dp), horizontalArrangement = Arrangement.End) {
                Button(onClick = {
                    showMain = true  // resetting game control variables for future rounds
                    showGame = false
                    userGuess = ""
                    sequence = -1
                    sequenceLen = -1
                    outcome = -1
                    generated = false
                    guessed = false
                    seqDisplayed = false
                })
                {
                    Text("Main")
                }
            }
            if (sequenceLen == -1) {  // a sequence length hasn't been chosen
                Row(modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
                    Text("Choose a sequence length: ")
                }
                Row(modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
                    Button(onClick = {
                        sequenceLen = 1
                    }) {
                        Text("1")
                    }
                    Button(onClick = {
                        sequenceLen = 2
                    }) {
                        Text("2")
                    }
                    Button(onClick = {
                        sequenceLen = 3
                    }) {
                        Text("3")
                    }
                    Button(onClick = {
                        sequenceLen = 4
                    }) {
                        Text("4")
                    }
                    Button(onClick = {
                        sequenceLen = 5
                    }) {
                        Text("5")
                    }
                }
                Row(modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
                    Button(onClick = {
                        sequenceLen = 6
                    }) {
                        Text("6")
                    }
                    Button(onClick = {
                        sequenceLen = 7
                    }) {
                        Text("7")
                    }
                    Button(onClick = {
                        sequenceLen = 8
                    }) {
                        Text("8")
                    }
                    Button(onClick = {
                        sequenceLen = 9
                    }) {
                        Text("9")
                    }
                    Button(onClick = {
                        sequenceLen = 10
                    }) {
                        Text("10")
                    }
                }
            }
            if (sequenceLen > -1) {  // a sequence length has been chosen
                if (!generated) {  // generating a sequence
                    sequence = ((10.0.pow(sequenceLen - 1).toInt()..< 10.0.pow(sequenceLen)  // Kotlin Foundation (JetBrains), (n.d.), Apache 2.0, https:kotlinlang.org/api/core/kotlin-stdlib/kotlin.math/pow.html
                        .toInt() - 1).random())
                    generated = !generated
                }

                // The following code is from Google, Gemini, "How to display a sequence of numbers with a 2-second gap between digits in kotlin jetpack compose?", 2026-10-01
                LaunchedEffect(sequence) {
                    for (char in sequence.toString()) {
                        currentDigit = char.toString()
                        delay(1000)
                    }
                    currentDigit = ""
                    seqDisplayed = true
                }

                if (!seqDisplayed) {
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
                        Text(currentDigit)
                    }
                }
                // End of code from Google, Gemini, "How to display a sequence of numbers with a 2-second gap between digits in kotlin jetpack compose?", 2026-10-01

                if (seqDisplayed && !guessed) {  // Prompting user to guess the sequence after all digits have been displayed
                    Row(modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
                        OutlinedTextField(
                            value = userGuess,
                            onValueChange = { userGuess = it },
                            label = { Text("Enter sequence: ") },
                            modifier = modifier.weight(1f)
                        )
                        Button({  // Logging attempt
                            attemptCount += 1
                            val clock: Clock = Clock.System  // Kotlin Foundation (JetBrains), (n.d.), Apache 2.0, https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.time/-instant/
                            val current_ts = clock.now()
                            if (userGuess == "" || userGuess.toInt() != sequence) {  // wrong guess
                                outcome = 0
                                game.addAttempt(
                                    Attempt(
                                        sequenceLen,
                                        userGuess.toInt(),
                                        sequence,
                                        false,
                                        current_ts
                                    )
                                )
                            } else {  // correct guess
                                outcome = 1
                                correctCount += 1
                                game.addAttempt(
                                    Attempt(
                                        sequenceLen,
                                        userGuess.toInt(),
                                        sequence,
                                        true,
                                        current_ts
                                    )
                                )
                            }
                            guessed = !guessed
                        }) {
                            Text("Confirm")
                        }
                    }
                }
                Row(modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {  // Informing user if their guess was correct or not
                    if (outcome == 1) {
                        Text("Correct! The sequence is: " + sequence.toString())
                    }
                    else if (outcome == 0) {
                        Text("Wrong - The correct sequence is: " + sequence.toString())
                    }
                }

            }
        }
    }
    if (showLog) {
        Column(modifier.fillMaxSize()) {
            Row(modifier.fillMaxWidth().padding(30.dp), horizontalArrangement = Arrangement.End) {
                Button(onClick = {
                    showMain = true
                    showLog = false
                })
                {
                    Text("Main")
                }
            }
            Row(modifier.fillMaxWidth().padding(5.dp), horizontalArrangement = Arrangement.Start) {
                Text("Length")
                Spacer(modifier.padding(15.dp))
                Text("Input")
                Spacer(modifier.padding(15.dp))
                Text("Actual")
                Spacer(modifier.padding(15.dp))
                Text("Correct")
                Spacer(modifier.padding(15.dp))
                Text("Time")
            }
            // I learned how to implement the LazyColumns from CMPUT 301 (Lab 3), (2026, May 25), Public Domain, https://github.com/cmput301-f26/lab-03 (code is in CityListScreen.kt)
            LazyColumn(modifier = Modifier.fillMaxSize()) {  // displaying info regarding each attempt
                itemsIndexed(game.attempts()) { index, attempt ->
                    AttemptRow(attempt = attempt)
                    if (index < game.attempts().lastIndex) {
                        HorizontalDivider()
                    }
                }
            }
        }
    }
    if (showSummary) {
        Column(modifier.fillMaxSize()) {
            Row(modifier.fillMaxWidth().padding(30.dp), horizontalArrangement = Arrangement.End) {
                Button(onClick = {
                    showMain = true
                    showSummary = false
                })
                {
                    Text("Main")
                }
            }
            Row(modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
                Text("Number of Attempts: " + attemptCount.toString())
            }
            Row(modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
                Text("Number of Correct Responses: " + correctCount.toString())
            }
            Row(modifier.fillMaxWidth(), horizontalArrangement = Arrangement.Center) {
                if (attemptCount == 0) {  // avoid 'division by zero' error
                    Text("Accuracy Rate: 0.0")
                }
                else {
                    Text("Accuracy Rate: " + (correctCount.toDouble()/attemptCount.toDouble()).toString())
                }
            }
        }
    }
}

// I learned how to implement the rows used in the LazyColumn from CMPUT 301 (Lab 3), (2026, May 25), Public Domain, https://github.com/cmput301-f26/lab-03 (code is in CityListScreen.kt)
@OptIn(ExperimentalTime::class)
@Composable
fun AttemptRow(attempt: Attempt) {  // printing attempt info one row at a time with all attributes
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 10.dp, vertical = 16.dp)
    ) {
        Text(
            text = attempt.sequenceLen.toString(),
            fontSize = 15.sp,
            modifier = Modifier.weight(1f)
        )

        Text(
            text = attempt.input.toString(),
            fontSize = 15.sp,
            modifier = Modifier.weight(1f)
        )
        Text(
            text = attempt.answer.toString(),
            fontSize = 15.sp,
            modifier = Modifier.weight(1f)
        )
        Text(
            text = attempt.correct.toString(),
            fontSize = 15.sp,
            modifier = Modifier.weight(1f)
        )
        Text(
            text = attempt.current_ts.toString(),
            fontSize = 15.sp,
            modifier = Modifier.weight(1f)
        )
    }
}